import { getSubtotal, getGSTAmount, getTotal, formatCurrency, getCurrencySymbol } from './calculations';
import { formatDate } from './invoiceNumber';

/**
 * Copy a formatted invoice summary text to the clipboard.
 * @param {Object} invoiceData - Full invoice state object
 * @returns {Promise<boolean>} - true on success
 */
export async function copyInvoiceSummary(invoiceData) {
  const {
    seller, buyer, invoice, items, gstRate, currency,
  } = invoiceData;

  const subtotal  = getSubtotal(items);
  const gstAmount = getGSTAmount(subtotal, gstRate);
  const total     = getTotal(subtotal, gstAmount);
  const sym       = getCurrencySymbol(currency);

  const lineRows = items
    .filter(i => i.description)
    .map((item, idx) => {
      const amt = (parseFloat(item.qty) || 0) * (parseFloat(item.rate) || 0);
      return `  ${idx + 1}. ${item.description.padEnd(30)} Qty: ${item.qty}  Rate: ${sym}${item.rate}  Amt: ${formatCurrency(amt, currency)}`;
    })
    .join('\n');

  const text = `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  INVOICE SUMMARY — ${invoice.number}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  FROM (Seller):
  ${seller.businessName}
  GST: ${seller.gstNumber || 'N/A'}
  ${seller.email} | ${seller.phone}
  ${seller.address}

  TO (Client):
  ${buyer.clientName}
  ${buyer.clientEmail}
  ${buyer.clientAddress}

  Invoice Date : ${formatDate(invoice.date)}
  Due Date     : ${formatDate(invoice.dueDate)}

  ─────────────────────────────────────────────────
  LINE ITEMS:
${lineRows}

  ─────────────────────────────────────────────────
  Subtotal   : ${formatCurrency(subtotal, currency)}
  GST (${gstRate}%)  : ${formatCurrency(gstAmount, currency)}
  GRAND TOTAL: ${formatCurrency(total, currency)}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by InvoiceForge
`.trim();

  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback for older browsers
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.style.position = 'fixed';
    ta.style.opacity  = '0';
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand('copy');
    document.body.removeChild(ta);
    return ok;
  }
}
